version: "3.7"

services:
  frontend:
    build:
      context: ./frontend
    command: yarn start
    volumes:
      - ./frontend/src:/usr/app/src
    ports:
      - "3000:3000"
    tty: true
    stdin_open: true
    environment:
      - REACT_APP_API_PORT=8080
      - REACT_APP_API_URL=api

  api:
    build:
      context: ./backend
    command: yarn run dev
    volumes:
      - ./backend/src:/usr/app/src
    ports:
      - "8080:8080"
    depends_on:
      - api_mongo
    environment:
      - CORS_PORT=3000
      - CORS_URL=frontend
      - MONGO_PORT="27017"
      - MONGO_URL="api_mongo"

  api_mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"

volumes:
  mongodb_api:
